name: Check Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install pnpm
        run: npm install -g pnpm # pnpm을 전역으로 설치

      - name: Install Dependencies
        run: pnpm install # pnpm을 사용하여 의존성 설치

      - name: Run Lint
        run: pnpm lint # 린트 실행

      - name: Run Prettier
        run: pnpm format --check # 프리티어 체크

      - name: Build # 머지하려는 브랜치가 main 브랜치이면 build:prod, dev 브랜치이면 build:dev
        run: pnpm build:${{ github.event.pull_request.base.ref == 'main' && 'prod' || 'dev' }}

  label:
    runs-on: ubuntu-latest
    needs: check # check 작업이 완료된 후 실행

    steps:
      - name: Add Labels
        if: github.event.pull_request.draft == false # 드래프트가 아닐 경우에만 실행
        uses: actions/add-labels@v1
        with:
          labels: ${{ github.event.pull_request.base.ref == 'dev' && 'dev' || github.event.pull_request.base.ref == 'main' && 'main'}} # dev로 머지 시 dev 라벨, main으로 머지 시 main 라벨
